

INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (332,331, 'system/tronAddress/list', '地址管理', '', '', '', 1, 10, 1, 1, 'tronAddress', '', 'system/tronAddress/list', 0, 'sys_admin', 0, NULL, '2022-04-16 03:34:25', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (333,332, 'system/tronAddress/get', '查询', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 01:22:04', NULL);



INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (334,331,  'system/tronCurrency/list', '币种管理', '', '', '', 1, 9, 1, 1, 'tronCurrency', '', 'system/tronCurrency/list', 0, 'sys_admin', 0, NULL, '2022-04-16 03:34:29', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (335, 334, 'system/tronCurrency/get', '查询', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:05:46', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (336, 334, 'system/tronCurrency/add', '添加', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:05:53', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (337, 334, 'system/tronCurrency/edit', '修改', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:05:58', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (338, 334, 'system/tronCurrency/delete', '删除', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:06:04', NULL);

INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (339,331,  'system/tronFeeList/list', '手续费管理', '', '', '', 1, 8, 1, 1, 'tronFeeList', '', 'system/tronFeeList/list', 0, 'sys_admin', 0, NULL, '2022-04-16 03:37:40', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (340, 339, 'system/tronFeeList/get', '查询', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:06:52', NULL);


INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (341,331, 'system/tronRecharge/list', '充值管理', '', '', '', 1, 7, 1, 1, 'tronRechargeList', '', 'system/tronRecharge/list', 0, 'sys_admin', 0, NULL, '2022-04-16 03:34:38', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (342, 341, 'system/tronRecharge/get', '查询', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:08:25', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (343, 341, 'system/tronRecharge/callback', '发起回调', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 03:41:55', NULL);


INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (345,331,  'system/tronWithdraw/list', '提现管理', '', '', '', 1, 6, 1, 1, 'tronWithdrawList', '', 'system/tronWithdraw/list', 0, 'sys_admin', 0, NULL, '2022-04-16 03:34:42', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (346, 345, 'system/tronWithdraw/get', '查询', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, NULL, '2022-04-16 02:08:35', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (347, 345, 'system/tronWithdraw/auditFail', '审核拒绝', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, '2022-04-16 17:24:49', '2022-04-16 17:24:49', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (348, 345, 'system/tronWithdraw/callback', '发起回调', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, '2022-04-16 03:45:50', '2022-04-16 03:45:50', NULL);
INSERT INTO `wallet`.`sys_auth_rule` (`id`, `pid`, `name`, `title`, `icon`, `condition`, `remark`, `menu_type`, `weigh`, `status`, `always_show`, `path`, `jump_path`, `component`, `is_frame`, `module_type`, `model_id`, `created_at`, `updated_at`, `deleted_at`) VALUES (349, 345, 'system/btronWithdraw/auditSuccess', '审核通过', '', '', '', 2, 0, 1, 1, '', '', '', 0, 'sys_admin', 0, '2022-04-16 17:24:22', '2022-04-16 17:24:22', NULL);
